# See https://github.com/actions/labeler

'pkg: workbox-build':
- changed-files:
  - packages/workbox/build/**

'pkg: workbox-cli':
- changed-files:
  - packages/workbox/cli/**

'pkg: workbox-swkit':
- changed-files:
  - packages/workbox/swkit/**

'pkg: workbox-types':
- changed-files:
  - packages/workbox/types/**

'pkg: workbox-window':
- changed-files:
  - packages/workbox/window/**

# Other categories
🚨 action:
  - changed-files:
    - .github/workflows/**
    - .github/actions/**

documentation:
- changed-files:
  - README.md
  - CONTRIBUTING.md
#  - packages/**/README.md
