# See https://github.com/actions/labeler

'pkg: workbox-build':
- changed-files:
  - packages/workbox/build/**

'pkg: workbox-cli':
- changed-files:
  - any-glob-to-any-file: 'packages/workbox/cli/**'

'pkg: workbox-swkit':
- changed-files:
  - any-glob-to-any-file: 'packages/workbox/swkit/**'

'pkg: workbox-types':
- changed-files:
  - any-glob-to-any-file: 'packages/workbox/types/**'

'pkg: workbox-window':
- changed-files:
  - any-glob-to-any-file: 'packages/workbox/window/**'

# Other categories
🚨 action:
- changed-files:
  - any-glob-to-any-file:
    - '.github/workflows/**'
    - '.github/actions/**'

documentation:
- changed-files:
  - any-glob-to-any-file:
    - 'README.md'
    - 'CONTRIBUTING.md'
