# See https://github.com/actions/labeler

'pkg: workbox-build':
- any:
  - changed-files:
    - packages/workbox/build/**

'pkg: workbox-cli':
- any:
  - changed-files:
    - packages/workbox/cli/**

'pkg: workbox-swkit':
- any:
  - changed-files:
    - packages/workbox/swkit/**

'pkg: workbox-types':
- any:
  - changed-files:
    - packages/workbox/types/**

'pkg: workbox-window':
- any:
  - changed-files:
    - packages/workbox/window/**

# Other categories
🚨 action:
- any:
  - changed-files:
    - .github/workflows/**
    - .github/actions/**

#documentation:
#  - README.md
#  - packages/**/README.md
