autoInstallPeers: true

catalogMode: prefer

cleanupUnusedCatalogs: true

dedupePeers: true

ignoreWorkspaceRootCheck: true

linkWorkspacePackages: true

verifyDepsBeforeRun: install

preferWorkspacePackages: true

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false

trustPolicy: no-downgrade

packages:
  - examples/**
  - packages/*

overrides:
  '@types/node': 'catalog:types'
  chokidar: ^5.0.0
  rolldown: 'catalog:utils'
  why-is-node-running: 'catalog:utils'

patchedDependencies:
  dotenv-expand@13.0.0: patches/dotenv-expand@13.0.0.patch

allowBuilds:
  '@parcel/watcher': false
  core-js: false
  esbuild: false

catalogs:
  build:
    tsdown: ^0.23.0
  docs:
    typedoc: ^0.28.20
  eslint:
    '@antfu/eslint-config': ^9.5.1
    eslint: ^10.11.0
    eslint-plugin-antfu: ^3.2.3
  rsbuild:
    '@rsbuild/core': ^2.2.11
  rspack:
    '@rspack/core': ^2.2.8
  test:
    '@vitest/ui': ^5.0.3
    vitest: ^5.0.3
  types:
    '@types/node': ^24.19.0
    '@types/serialize-javascript': ^5.0.4
    '@types/trusted-types': ^2.0.7
    '@types/webpack': ^5.28.5
  typescript:
    typescript: ~6.0.3
  utils:
    '@antfu/ni': ^25.0.0
    '@arethetypeswrong/core': ^0.18.5
    '@clack/prompts': ^1.8.1
    '@jridgewell/remapping': ^2.3.5
    ansis: ^4.4.0
    cac: ^7.0.0
    consola: ^3.4.2
    dotenv-expand: 13.0.0
    idb: ^8.0.3
    magic-string: ^1.4.2
    magicast: ^0.5.5
    proper-tags: ^2.0.2
    publint: ^0.3.24
    rolldown: ^1.2.12
    "@rolldown/pluginutils": ^1.0.1
    serialize-javascript: ^7.1.2
    std-env: ^4.3.0
    taze: 21.1.0
    tinyglobby: ^0.2.17
    unrun: ^0.3.1
    valibot: ^1.5.0
    verkit: ^0.5.0
    why-is-node-running: 3.2.1
  vite:
    vite: ^8.3.1
  webpack5:
    webpack: ^5.111.1

minimumReleaseAge: 10080 # minutes = 7 days

minimumReleaseAgeExclude:
  - vite@8.3.1
  - verkit@0.5.0
