packages:
  - packages/*

autoInstallPeers: true

overrides:

catalogs:
  build:
    bumpp: ^10.3.1
    tsdown: ^0.15.7

  eslint:
    '@antfu/eslint-config': ^6.0.0
    eslint: ^9.37.0
    eslint-plugin-antfu: ^3.1.1

  types:
    '@types/node': ^22.9.3
    '@types/trusted-types': ^2.0.7

  typescript:
    '@typescript-eslint/utils': ^8.45.0
    typescript: ~5.9.3

  utils:
    '@antfu/ni': ^25.0.0
    '@arethetypeswrong/cli': ^0.17.4
    taze: ^19.7.0

cleanupUnusedCatalogs: true

ignoreWorkspaceRootCheck: true

shamefullyHoist: true

shell-emulator: true

strictPeerDependencies: false
