packages:
  - packages/*

autoInstallPeers: true

catalogs:
  build:
    bumpp: ^10.3.1
    tsdown: https://pkg.pr.new/tsdown@c4f9764
  eslint:
    '@antfu/eslint-config': ^6.0.0
    eslint: ^9.37.0
    eslint-plugin-antfu: ^3.1.1
  testing:
    '@vitest/ui': ^3.2.4
    vitest: ^3.2.4
  types:
    '@types/node': ^22.9.3
    '@types/trusted-types': ^2.0.7
  typescript:
    '@typescript-eslint/utils': ^8.45.0
    typescript: ~5.9.3
  utils:
    '@antfu/ni': ^25.0.0
    '@arethetypeswrong/cli': ^0.17.4
    idb: ^8.0.3
    pathe: ^2.0.3
    pkg-types: ^2.3.0
    proper-tags: ^2.0.2
    recast: ^0.23.11
    taze: ^19.7.0
    valibot: ^1.1.0

cleanupUnusedCatalogs: true

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false
